server:
  port: 8080

spring:
  #Connect to the Redis Memory Bank
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: crawl-service
          uri: http://localhost:8081
          predicates:
            - Path=/crawl/**

        - id: search-service
          uri: http://localhost:8082
          predicates:
            - Path=/search/**
          # Add the Filter mathematically throttling IPs
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5 #Add 5 tokens per second
                redis-rate-limiter.burstCapacity: 10 #Max 10 absolute simultaneous requests
                redis-rate-limiter.requestedTokens: 1 #Cost: 1 Token per request

  

# Push 100% of Traces to the Zipkin UI
management:
  tracing:
    sampling:
      probability: 1.0 # Tells Micrometer to send every single trace to Zipkin
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      