server:
  port: 8083 # Optional port for a pure consumer service

spring:
  application:
    name: indexer-service
  
  # Connect to our Message Broker
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: indexer-group # If we run 5 instances of the indexer, they share the load instead of doing duplicate work!
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.omnisearch.common" # Crucial: Allows Kafka to decode your PageCrawledEvent object safely.

  # Connect to our Database
  elasticsearch:
    uris: localhost:9200
